version: "3.8"

services:
    nodeserver:
        build:
            context: ./app
        ports:
            - "6000:6000"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "8080:8080"